from typing import Dict
from ..models.category_priority import Category
# from ..models.difficulty_profile import DifficultyAssessment
from ..models.difficulty_profile import Difficulty
from ..models.interview_slot import InterviewSlot
from ..models.interview_blueprint import InterviewBlueprint

class BlueprintBuilder:
    def build(
        self,
        total_questions: int,
        category_allocations: Dict[Category, int],
        difficulty_matrix: Dict[Category, Dict[Difficulty, int]]
    ) -> InterviewBlueprint:
        
        difficulty_allocations = {difficulty: 0 for difficulty in Difficulty}
        slots = []
        question_number = 1
        
        for category in Category:
            category_matrix = difficulty_matrix.get(category, {difficulty: 0 for difficulty in Difficulty})
                
            for difficulty in Difficulty:
                count = category_matrix.get(difficulty, 0)
                for _ in range(count):
                    slots.append(
                        InterviewSlot(
                            question_number=question_number,
                            category=category,
                            difficulty=difficulty,
                            allowed_context=[],
                            follow_up_allowed=False
                        )
                    )
                    question_number += 1
                    difficulty_allocations[difficulty] += 1
                    
        return InterviewBlueprint(
            total_questions=total_questions,
            category_allocations=category_allocations,
            difficulty_allocations=difficulty_allocations,
            question_slots=slots,
            generation_notes="Generated by BlueprintBuilder"
        )
