from typing import Dict
from ..models.category_priority import Category
from ..models.difficulty_profile import DifficultyAssessment, Difficulty
from ..models.interview_slot import InterviewSlot
from ..models.interview_blueprint import InterviewBlueprint

class BlueprintBuilder:
    def build(
        self,
        total_questions: int,
        category_allocations: Dict[Category, int],
        difficulty_assessment: DifficultyAssessment
    ) -> InterviewBlueprint:
        
        difficulty_allocations = {d: 0 for d in Difficulty}
        slots = []
        q_num = 1
        
        for cat, count in category_allocations.items():
            if count == 0:
                continue
                
            if hasattr(difficulty_assessment.category_difficulty_preferences, cat.value):
                dist = getattr(difficulty_assessment.category_difficulty_preferences, cat.value)
            else:
                dist = difficulty_assessment.difficulty_profile
                
            targets = {
                Difficulty.EASY: dist.easy * count,
                Difficulty.MEDIUM: dist.medium * count,
                Difficulty.HARD: dist.hard * count,
                Difficulty.EXPERT: dist.expert * count,
            }
            
            cat_diffs = {d: 0 for d in Difficulty}
            rem = count
            
            while rem > 0:
                best_diff = sorted(targets.items(), key=lambda x: x[1], reverse=True)[0][0]
                cat_diffs[best_diff] += 1
                targets[best_diff] -= 1
                rem -= 1
                
            for diff, cnt in cat_diffs.items():
                for _ in range(cnt):
                    slots.append(
                        InterviewSlot(
                            question_number=q_num,
                            category=cat,
                            difficulty=diff,
                            allowed_context=[],
                            follow_up_allowed=False
                        )
                    )
                    q_num += 1
                    difficulty_allocations[diff] += 1
                    
        return InterviewBlueprint(
            total_questions=total_questions,
            category_allocations=category_allocations,
            difficulty_allocations=difficulty_allocations,
            question_slots=slots,
            generation_notes="Generated by BlueprintBuilder"
        )
